### ISSUE TITLE
Joining appeal server when not banned leads to incorrect order of join/leave embeds

### ISSUE THREAD

**Issue by TizzySaurus** [python-discord/modmail-plugins#21]
Currently when a user has a ModMail thread open, and attempts to join the appeals server when they aren't banned, their thread will have two embeds sent: one notifying of the user joining, and one notifying of the user leaving.

The issue with the current implementation, is that the leave embed is sent before the join embed, which can be misleading and confusing.

An example can be seen below:
![image](https://user-images.githubusercontent.com/47674925/155720756-1fcba4a3-f5af-423c-89cc-bcac739aeb7a.png)

In terms of a fix, it should just be a case of moving the code for sending the join message, to above the `_maybe_kick_user` function call inside the [`on_member_join` event](https://github.com/python-discord/modmail-plugins/blob/main/ban_appeals/ban_appeals.py#L115-L126), however @ChrisLovering seems to have concerns with this approach.

Once a fix is decided upon, I'd like to implement it.

**Comment by Qwerty-133** [comment]
This has already been fixed in #19.
